<html>
<head>
    <style type="text/css" title="text/css">
        <!--
        body {
            margin: 0em 1em;
            width: 50em;
        }

        tt {
            color: #7BB84A;
            font-size: inherited;
            font-family: inherited;
        }

        -->
    </style>
</head>
<body>
<br/>

<p>Welcome to the Birk demopage.</p>

<p>Birk is Wayf.dk's "Reverse Peer to Peer Federation in a Box". To the outside it looks like 92 IDPs and to the inside
    (wayf.dk) it looks like currently 2 SPs. Birk allows wayf.dk to act as a peer to peer federation while keeping the
    operating complexity
    and costs low as all the IDPs still only need to use one rather permanent set of metadata.</p>

<p>The 92 idps are proxies for the federations "real" IDPs, which normally are "hidden" behind wayf.dk. They are exposed
    as individual IDPs because some SPs like to host the discovery themselves but does not support SAML scoping.</p>

<p>The SPs are proxies for the "real" SPs. They are exposed to wayf.dk because then wayf.dk can handle consent as if it
    was communicating directly with the real SPs. In the future wayf.dk might support the explicit proxying of the IDPs
    itself and then the need for proxying of the SPs goes away.</p>

<p>For this POC all entities (ie. the IDPs, the proxied IDPs, the SPs, the proxied SPs and wayf) are hosted on a Corto
    installation.</p>

<p>Select a SP and an IDP and press "Demo". The request then goes:
<ol>
    <li>from the selected SP</li>
    <li>to (a proxied version of) the selected IDP where is is scoped to wayf and the real IDP and then sent</li>
    <li>to a proxied version of the original SP ("inside" Birk) which sends it</li>
    <li>to the proxy/wayf which sends it</li>
    <li>to the real IDP (which for this demonstration uses the null auth as a backend IDP)</li>
</ol>
</p>
<p>Look at the RequesterIDs in the request at the bottom of the null auth page to se the path.</p>

<p>Click "GO" at the null auth page to send the response back the reverse route and then look at the
    AuthenticationAuthorities in the resulting assertion - which will be displayed below.</p>

<form method=POST action="<?php echo $action ?>">
    Select SP:<select name="sp">
    <option>ude@evil</option>
    <option>moc.elgoog</option>
</select>

    <p>
       Select IDP: <select name="idp">
        <?php echo "<option>" . join("</option><option>", $idplist) . "</option>"; ?>
        </select>
    </p>
    <p>    <input type=hidden name=doit value=1> <input type=submit value="Demo">
</p>
</form>

<p><?php echo $message ?></p>
<pre>
<?php echo preg_replace("/\n\n/", "\n", preg_replace("/Array\n\s+/", "Array ", htmlspecialchars(print_r($SAMLResponse, 1)))); ?>
        </pre>
</body>
</html>
