<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
        "http://www.w3.org/TR/html4/loose.dtd">
<html>
    <head>
        <title>Discover ...</title>
    </head>
    <body>
        <form method="post" action="<?php echo $action ?>">
            <input type="hidden" name="ID" value="<?php echo $ID ?>" />
            <select name="idp">
                <?php foreach($idpList as $idp): ?>
                <option value="<?php echo $idp ?>"><?php echo $idp ?></option>
                <?php endforeach ?>
            </select>
            <input type=submit value=Send>
        </form>
    </body>
</html>