<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title>POST data</title>
</head>
<body <?php if ( !$trace): ?> onload="document.forms[0].submit()"
<?php endif; ?>>
<noscript>
<p><strong>Note:</strong> Since your browser does not support
JavaScript, you must press the button below once to proceed.</p>
</noscript>
<form method="post" action=" <?php echo $action ?>"><input type="hidden"
	name="<?php echo $name ?>" value="<?php echo $message ?>" /> <?php echo $xtra ?>

<noscript><input type="submit" value="Submit" /></noscript>

	<?php if ($trace): ?> <input type="submit" value="Submit" /> <pre>
	<?php echo $trace ?>
            </pre> <?php endif; ?></form>
</body>
</html>
