<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
        "http://www.w3.org/TR/html4/loose.dtd">
<html>
    <head>
        <title>Consent</title>
    </head>
    <body>
        <form method="post" action="<?= $action ?>">
            <input type="hidden" name="ID" value="<?= $ID ?>" />
            <input type="hidden" name="consent" value="yes" />
            Do you consent to the following information being sent to your Service Provider:
            <pre>
            <? print_r($attributes) ?>
            </pre>
            <input type=submit value=Send>
        </form>
    </body>
</html>