<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
        "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<title>Consent</title>
</head>
<body>
<form method="post" action="<?php echo $action ?>"><input type="hidden"
	name="ID" value="<?php echo $ID ?>" /> <input type="hidden"
	name="consent" value="yes" /> Do you consent to the following
information being sent to your Service Provider: <?php foreach ($attributes as $uid => $attributeValues) { ?>
<dl style="margin-left: 60px;">
	<dt style="font-weight: bold;"><?php echo $this->getAttributeName($uid, 'nl_NL')?>
	</dt>
	<dd><?php /** Single attribute value */ if (count($attributeValues)==1) { ?>
	<?php echo $attributeValues[0];?> <?php } /** Multiple attribute values */ else { ?>
	<ul>
	<?php foreach ($attributeValues as $value) { ?>
		<li><?php echo $value?></li>
		<?php } ?>
	</ul>
	<?php } ?></dd>
</dl>
	<?php } ?> <input type=submit value=Send></form>
</body>
</html>
